services:
#    ceeps_mailer.example:
#        class: Ceeps\MailerBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    seta_mailing:
        class: Ceeps\MailerBundle\Business\MailService
        arguments: [ @system_mailer ]