<?php

namespace Seta\RentalBundle\Repository;

use Seta\ResourceBundle\Doctrine\ORM\EntityRepository;

/**
 * QueueRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QueueRepository extends EntityRepository
{
}
