<?php

namespace Seta\RentalBundle\Repository;

use Seta\LockerBundle\Entity\Locker;
use Seta\RentalBundle\Exception\NotFoundRentalException;
use Seta\ResourceBundle\Doctrine\ORM\EntityRepository;
use Seta\UserBundle\Entity\User;

/**
 * RentalRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @codeCoverageIgnore
 */
class RentalRepository extends EntityRepository implements RentalRepositoryInterface
{
    public function getLastRentals(User $user, $limit = 10)
    {
        $queryBuilder = $this->getQueryBuilder();

        $queryBuilder
            ->andWhere($queryBuilder->expr()->eq('o.user', ':user'))
            ->orderBy('o.startAt', 'DESC')
            ->setParameter('user', $user)
            ->setMaxResults($limit)
        ;

        return $queryBuilder->getQuery()->getResult();
    }

    public function getCurrentRental(Locker $locker)
    {
        $queryBuilder = $this->getQueryBuilder();

        $queryBuilder
            ->andWhere($queryBuilder->expr()->eq('o.user', ':user'))
            ->andWhere($queryBuilder->expr()->eq('o.locker', ':locker'))
            ->andWhere($queryBuilder->expr()->isNull('o.returnAt'))
            ->setParameter('user', $locker->getOwner())
            ->setParameter('locker', $locker)
        ;

        $rental = $queryBuilder->getQuery()->getOneOrNullResult();

        if (!$rental) {
            throw new NotFoundRentalException();
        }

        return $rental;
    }

    public function getExpireOnDateRentals(\DateTime $on)
    {
        $start = clone $on;
        $end = clone $on;
        $start->setTime(0, 0, 0);
        $end->setTime(23, 59, 59);

        $queryBuilder = $this->getQueryBuilder();

        $queryBuilder
            ->andWhere($queryBuilder->expr()->between('o.endAt', ':start', ':end'))
            ->andWhere($queryBuilder->expr()->isNull('o.returnAt'))
            ->setParameter('start', $start)
            ->setParameter('end', $end)
        ;

        return $queryBuilder->getQuery()->getResult();
    }
}
