version: '2'

services:
    application:
        build: 'docker/code'
        volumes:
            - '.:/var/www/symfony'
            - './docker/logs/symfony:/var/www/symfony/var/logs'
            - './docker/etc/parameters.yml:/etc/credentials/seta.yml'
            - '../../simplesamlphp/simplesamlphp:/var/simplesamlphp'
        tty: true
    php:
        build: 'docker/php7-fpm'
        expose:
            - '9001'
        volumes_from:
            - 'application'
        external_links:
            - 'db'
        environment:
            - 'SYMFONY_ENV=dev'
        networks:
            - 'mysql_default'
            - 'default'
    nginx:
        build: 'docker/nginx'
        ports:
            - '127.0.0.1:80:80'
        links:
            - 'php'
        volumes_from:
            - 'application'
        volumes:
            - './docker/logs/nginx/:/var/log/nginx'
        networks:
            - 'default'

networks:
    mysql_default:
        external: true

