easy_admin:
    site_name: 'tUCOnsigna'

    entities:
        User:
            class: AppBundle\Entity\User
            list:
                fields:
                    - { property: 'username', label: 'label.username' }
                    - { property: 'email', label: 'label.email' }
                    - { property: 'enabled', type: 'toggle', label: 'label.enabled' }
                    - { property: 'locked', type: 'toggle', label: 'label.locked' }
                    - { property: 'lastLogin', label: 'label.lastLogin' }
                actions:
                    - { name: 'show', icon: 'search', label: '' }
                    - { name: 'edit', icon: 'pencil', label: '' }
                    - { name: 'assign', type: 'method', icon: 'lock', label: '' }
            form:
                fields:
                    - { property: 'username', label: 'label.username' }
                    - { property: 'email', type: 'email', label: 'label.email' }
                    - { property: 'plainPassword', type: 'password', label: 'label.password', help: 'help.password' }
                    - { property: 'enabled', type: 'checkbox', label: 'label.enabled' }
                    - { property: 'locked', type: 'checkbox', label: 'label.locked' }
        Locker:
            class: AppBundle\Entity\Locker
