ceeps_mailer:
    resource: "@CeepsMailerBundle/Controller/"
    type:     annotation
    prefix:   /

ceeps_penalty:
    resource: "@CeepsPenaltyBundle/Controller/"
    type:     annotation
    prefix:   /

ceeps_resource:
    resource: "@CeepsResourceBundle/Controller/"
    type:     annotation
    prefix:   /

rental:
    resource: "@CeepsRentalBundle/Controller/"
    type:     annotation
    prefix:   /

locker:
    resource: "@CeepsLockerBundle/Controller/"
    type:     annotation
    prefix:   /

ceeps_user:
    resource: "@CeepsUserBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
