fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

ceeps_userbundle:
    resource: "@CeepsUserBundle/Resources/config/routing.yml"

craue_config_settings:
  resource: "@CraueConfigBundle/Resources/config/routing/settings.xml"
  prefix: /admin/settings

easy_admin_bundle:
    resource: "@SetaCoreBundle/Controller/Backend/"
    type:     annotation
    prefix:   /admin

seta_core:
    resource: "@SetaCoreBundle/Controller/Frontend/"
    type:     annotation
    prefix:   /
