# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: 'bcrypt'

    role_hierarchy:
        ROLE_ADMIN:       'ROLE_USER'
        ROLE_SUPER_ADMIN: 'ROLE_ADMIN'

    providers:
        seta_user_provider:
            id: 'seta.user.provider'

    firewalls:
        dev:
            pattern:  '^/(_(profiler|wdt)|css|images|js)/'
            security: false
        api:
            pattern: '^/api/'
            security: false
        main:
            pattern: '^/'
            guard:
                provider: 'seta_user_provider'
                authenticators:
                    - 'uco.admin.authenticator'
            form_login:
                always_use_default_target_path: false
                target_path_parameter:          '_target_path'
            logout:
                path: '/logout'
                target: '/'
            anonymous:   true
            switch_user: true

    access_control:
        - { path: '^/login$', role: 'IS_AUTHENTICATED_ANONYMOUSLY' }
        - { path: '^/connect', role: 'IS_AUTHENTICATED_ANONYMOUSLY' }
        - { path: '^/check', role: 'ROLE_ADMIN' }
        - { path: '^/admin', role: 'ROLE_ADMIN' }
        - { path: '^/', role: 'IS_AUTHENTICATED_ANONYMOUSLY' }
        - { path: '^/*', role: 'ROLE_USER' }
