<?php

namespace Ceeps\LockerBundle\Repository;

use Ceeps\LockerBundle\Entity\Locker;
use Ceeps\ResourceBundle\Doctrine\ORM\EntityRepository;

/**
 * LockerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LockerRepository extends EntityRepository
{
    public function findOneFreeLocker()
    {
        $qb = $this->createQueryBuilder('l');

        $qb
            ->andWhere($qb->expr()->eq('l.status', ':enabled'))
            ->setParameter('enabled', Locker::AVAILABLE)
            ->setMaxResults(1)
        ;

        return $qb->getQuery()->getOneOrNullResult();
    }
}
