<?php

namespace Ceeps\RentalBundle\Repository;

use Ceeps\ResourceBundle\Doctrine\ORM\EntityRepository;

/**
 * QueueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QueueRepository extends EntityRepository
{
}
