<?php

namespace Ceeps\RentalBundle\Repository;

use Ceeps\LockerBundle\Entity\Locker;
use Ceeps\ResourceBundle\Doctrine\ORM\EntityRepository;

/**
 * RentalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @codeCoverageIgnore
 */
class RentalRepository extends EntityRepository
{
    public function getCurrentRental(Locker $locker)
    {
        $queryBuilder = $this->getQueryBuilder();

        $queryBuilder
            ->andWhere($queryBuilder->expr()->eq('o.user', ':user'))
            ->andWhere($queryBuilder->expr()->eq('o.locker', ':locker'))
            ->andWhere($queryBuilder->expr()->isNull('o.returnAt'))
            ->setParameter('user', $locker->getOwner())
            ->setParameter('locker', $locker)
        ;

        return $queryBuilder->getQuery()->getOneOrNullResult();

    }
}
