<?php

namespace Ceeps\RentalBundle\Repository;

use Ceeps\ResourceBundle\Doctrine\ORM\EntityRepository;

/**
 * RentalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @codeCoverageIgnore
 */
class RentalRepository extends EntityRepository
{
}
