<?php

namespace Ceeps\PenaltyBundle\Repository;

use Ceeps\ResourceBundle\Doctrine\ORM\EntityRepository;

/**
 * PenaltyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PenaltyRepository extends EntityRepository
{
}
