services:
#    seta_penalty.example:
#        class: Seta\PenaltyBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    seta.repository.penalty:
        class: Seta\PenaltyBundle\Repository\PenaltyRepository
        arguments: [ SetaPenaltyBundle:Penalty ]
        factory: [ @doctrine, getRepository ]
    seta.service.penalty:
        class: Seta\PenaltyBundle\Business\PenaltyService
        arguments: [ @doctrine.orm.default_entity_manager, @seta.repository.penalty ]
