easy_admin:
    site_name: '[SETA] Taquillas'
    formats:
        date: 'd/m/Y'
        datetime: 'd/m/Y'
        number: '%2.2f'
    design:
        form_theme: 'vertical'
        assets:
            css:
                - 'bundles/setaresource/css/seta.css'
                - 'bundles/sgomezbsdatetimepicker/css/bootstrap-datetimepicker.min.css'
        menu:
            - { entity: 'User', icon: 'user', params: { sortDirection: 'ASC' } }
            - { entity: 'Faculty', icon: 'bank', params: { sortDirection: 'ASC' } }
            - { entity: 'Locker', icon: 'archive', params: { sortDirection: 'ASC' } }
            - { entity: 'Rental', icon: 'calendar-o', params: { sortDirection: 'ASC' } }
            - label: 'app.menu.penalties'
              icon: 'lock'
              children:
                - { entity: 'TimePenalty', icon: 'clock-o' }
                - { entity: 'FinancialPenalty', icon: 'eur' }

            - { label: 'app.menu.settings', icon: 'cogs', route: 'craue_config_settings_modify' }