easy_admin:
    site_name: '[SETA] Taquillas'
    formats:
        date: 'd/m/Y'
        datetime: 'd/m/Y'
        number: '%2.2f'
    design:
        form_theme: 'vertical'
        assets:
            css:
                - 'bundles/setaresource/css/seta.css'
                - 'bundles/sgomezbsdatetimepicker/css/bootstrap-datetimepicker.min.css'
        menu:
            - { label: 'app.menu.new_rental', icon: 'plus', route: 'seta_backend_rental_new' }
            - { entity: 'User', icon: 'user', params: { sortField: 'username', sortDirection: 'ASC' } }
            - { entity: 'Rental', icon: 'calendar-o', params: { sortField: 'endAt', sortDirection: 'DESC' } }
            - label: 'app.menu.organization'
              icon: 'sitemap'
              children:
                - { entity: 'Faculty', icon: 'bank', params: { sortField: 'name', sortDirection: 'ASC' } }
                - { entity: 'Locker', icon: 'archive', params: { sortField: 'code', sortDirection: 'ASC' } }
                - { entity: 'Zone', icon: 'map-marker', params: { sortField: 'name', sortDirection: 'ASC' } }
            - label: 'app.menu.penalties'
              icon: 'lock'
              children:
                - { entity: 'TimePenalty', icon: 'clock-o' }
                - { entity: 'FinancialPenalty', icon: 'eur' }

            - { label: 'app.menu.settings', icon: 'cogs', route: 'craue_config_settings_modify' }
            - { label: 'app.menu.logout', icon: 'sign-out', route: 'fos_user_security_logout'}