easy_admin:
    site_name: '[SETA] Taquillas'
    formats:
        date: 'd/m/Y'
        datetime: 'd/m/Y'
        number: '%d'
    design:
        form_theme: 'vertical'
        assets:
            css:
                - 'bundles/setaresource/css/seta.css'
                - 'bundles/sgomezbsdatetimepicker/css/bootstrap-datetimepicker.min.css'
        menu:
            - { label: 'User', icon: 'user', entity: 'User' }
            - { label: 'Locker', icon: 'archive', entity: 'Locker' }
            - { label: 'Rental', icon: 'calendar-o', entity: 'Rental' }
            - { label: 'Penalty', icon: 'lock', entity: 'Penalty' }
            - { label: 'Settings', route: 'craue_config_settings_modify', icon: 'cogs' }