easy_admin:
    entities:
        Rental:
            class: Seta\RentalBundle\Entity\Rental
            label: app.menu.rentals
            disabled_actions: [ 'new', 'delete']
            list:
                actions:
                    - '-show'
                    - { name: 'edit', icon: 'edit' }
                    - { name: 'rental_renew', type: 'route', label: 'app.action.renew_rental', icon: 'refresh' }
                    - { name: 'rental_return', type: 'route', label: 'app.action.return_rental', icon: 'undo' }
                fields:
                    - { property: 'locker', label: 'label.locker' }
                    - { property: 'user', label: 'label.owner' }
                    - { property: 'startAt', label: 'label.start_at' }
                    - { property: 'endAt', label: 'label.end_at' }
                    - { property: 'isRenewable', type: 'toggle', label: 'label.is_renewable' }
            form:
                fields:
                    - { property: 'user', label: 'label.owner', type_options: { disabled: true } }
                    - { property: 'locker', label: 'label.locker', type_options: { disabled: true } }
                    - { property: 'endAt', type: 'Sgomez\BsDatetimepickerBundle\Form\Type\BsDateType', label: 'label.end_at', type_options: { config: { 'weekStart': 1 } } }
                    - { property: 'isRenewable', type: 'text', label: 'label.is_renewable' }
            show:
                fields:
                    - { property: 'user', label: 'label.owner' }
                    - { property: 'locker', label: 'label.locker' }
                    - { property: 'startAt', label: 'label.start_at' }
                    - { property: 'endAt', label: 'label.end_at' }
                    - { property: 'returnAt', label: 'label.return_at' }
                    - { property: 'isRenewable', type: 'toggle', label: 'label.is_renewable' }

