easy_admin:
    entities:
        TimePenalty:
            class: Seta\PenaltyBundle\Entity\TimePenalty
            label: app.menu.time_penalties
            disabled_actions: ['delete', 'new']
            list:
                actions:
                    - 'edit'
                    - { name: 'penalty_close', type: 'route', label: 'app.action.penalty_close' }
                fields:
                    - { property: 'user', label: 'label.user' }
                    - { property: 'rental', label: 'label.rental' }
                    - { property: 'startAt', type: 'date', label: 'label.start_at' }
                    - { property: 'endAt', type: 'date', label: 'label.end_at' }
                    - { property: 'status', label: 'label.status', template: 'status', trans: true}
            show:
                fields:
                    - { property: 'user', label: 'label.owner' }
                    - { property: 'rental.startAt', type: 'datetime', label: 'label.penalty_start_at' }
                    - { property: 'startAt', label: 'label.penalty_start_at' }
                    - { property: 'endAt', label: 'label.penalty_end_at' }
                    - { property: 'comment', label: 'label.comment' }
            form:
                fields:
                    - { property: 'user', label: 'label.user' }
                    - { property: 'endAt', type: 'Sgomez\BsDatetimepickerBundle\Form\Type\BsDateType', label: 'label.end_at', type_options: { config: { 'weekStart': 1 } } }
                    - { property: 'comment', label: 'label.comment' }
        FinancialPenalty:
            class: Seta\PenaltyBundle\Entity\FinancialPenalty
            label: app.menu.financial_penalties
            disabled_actions: ['delete']
            list:
                actions:
                    - 'edit'
                    - { name: 'penalty_close', type: 'route', label: 'app.action.penalty_close' }
                fields:
                    - { property: 'user', label: 'label.user' }
                    - { property: 'rental', label: 'label.rental' }
                    - { property: 'amount', type: 'float', label: 'label.amount' }
                    - { property: 'isPaid', type: 'boolean', label: 'label.is_paid' }
                    - { property: 'status', label: 'label.status', template: 'status', trans: true}
            form:
                fields:
                    - { property: 'user', label: 'label.user' }
                    - { property: 'amount', type: 'money', label: 'label.amount' }
                    - { property: 'comment', label: 'label.comment' }
