services:
#    locker.example:
#        class: Ceeps\LockerBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    tuconsigna.repository.locker:
        class: Ceeps\LockerBundle\Behat\LockerContext
        arguments: [ CeepsLockerBundle:Locker ]
        factory: [ @doctrine, getRepository ]